# Generated by Django 3.0.7 on 2020-08-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('mobile', models.IntegerField(max_length=10, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
