# Generated by Django 3.0.7 on 2020-08-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleform',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
